# Generated by Django 2.2.5 on 2019-11-16 00:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=core.models.upload_image_logo)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
