# Generated by Django 2.2.2 on 2020-03-26 02:30

import blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Titulo')),
            ],
            options={
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Titulo')),
                ('short_description', models.CharField(max_length=400, verbose_name='Descripcion corta')),
                ('content', ckeditor.fields.RichTextField()),
                ('presentation', models.ImageField(upload_to=blog.models.upload_image_blog, verbose_name='Portada')),
                ('date', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='entries', related_query_name='categories', to='blog.Category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Entrada',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Titulo')),
                ('link', models.URLField(verbose_name='enlace')),
                ('entries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', related_query_name='entrie', to='blog.Entry')),
            ],
            options={
                'verbose_name': 'Accion',
                'verbose_name_plural': 'Acciones',
            },
        ),
    ]
