# Generated by Django 2.2.5 on 2019-11-19 23:36

import blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Titulo')),
                ('slug', models.SlugField(editable=False)),
                ('content', ckeditor.fields.RichTextField()),
                ('presentation', models.ImageField(upload_to=blog.models.upload_image_blog, verbose_name='Portada')),
                ('date', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='entries', related_query_name='categories', to='blog.Category', verbose_name='Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Titulo')),
                ('link', models.URLField(verbose_name='enlace')),
                ('entrie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', related_query_name='entrie', to='blog.Entry')),
            ],
        ),
    ]
