# Generated by Django 2.2.2 on 2020-03-26 14:33

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('presentation', models.ImageField(upload_to=movies.models.upload_image_movie, verbose_name='Portada')),
                ('has_new_histories', models.BooleanField(default=False)),
                ('number_seasons', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('presentation', models.ImageField(upload_to=movies.models.upload_image_movie, verbose_name='Portada')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies.Serie', verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='Capitule',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('presentation', models.ImageField(upload_to=movies.models.upload_image_movie, verbose_name='Portada')),
                ('duration', models.CharField(max_length=5)),
                ('capitule', models.FileField(blank=True, null=True, upload_to=movies.models.upload_capitule)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitules', to='movies.Season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
            },
        ),
    ]
