# Generated by Django 2.2.5 on 2019-11-02 23:00

from django.db import migrations, models
import django.db.models.deletion
import movies.fields
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('date', models.DateTimeField(verbose_name='Fecha de publicacion')),
                ('presentation', models.ImageField(upload_to=movies.models.upload_image_movie, verbose_name='Portada')),
                ('has_new_histories', models.BooleanField()),
                ('number_seasons', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('date', models.DateTimeField(verbose_name='Fecha de publicacion')),
                ('presentation', models.ImageField(upload_to=movies.models.upload_image_movie, verbose_name='Portada')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies.Serie', verbose_name='Serie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capitule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('date', models.DateTimeField(verbose_name='Fecha de publicacion')),
                ('presentation', models.ImageField(upload_to=movies.models.upload_image_movie, verbose_name='Portada')),
                ('duration', movies.fields.DurationField(max_length=10)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitules', to='movies.Season', verbose_name='Temporada')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
