# Generated by Django 2.2.5 on 2019-11-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitule',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='season',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion'),
        ),
    ]
