# Generated by Django 2.2.5 on 2019-11-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191102_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='has_new_histories',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serie',
            name='number_seasons',
            field=models.IntegerField(default=0),
        ),
    ]
