# Generated by Django 2.2.5 on 2019-11-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191103_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitule',
            options={'verbose_name': 'Capitulo', 'verbose_name_plural': 'Capitulos'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
    ]
